version: 2.0

jobs:
  deploy:
    working_directory: ~/natsu.me
    machine: true
    steps:
      - checkout
      - run:
          name: deploy natsu.me
          command: aws s3 sync ~/natsu.me/ s3://natsu.me --region ap-northeast-2 --delete --exclude ".git/*" --exclude ".circleci/*"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

